application_locations_homepage:
    path:     /
    defaults: { _controller: applicationLocationsBundle:Default:index }

application_equipment_save:
    path:   /equipment/add
    default: { _controller: applicationLocationBundle:Location:saveEquipment}

equipmnet_add:
    path:   /equipmentadd
    default: { _contoller: applicationLocationBundle:Location:add}


