application_locations_homepage:
    path:     /
    defaults: { _controller: applicationLocationsBundle:Default:index }

application_equipmnet_add:
    path:   /locationadd
    defaults: { _controller: applicationLocationsBundle:Location:add}

application_equipment_save:
    path:   /location/add
    defaults: { _controller: applicationLocationsBundle:Location:saveLocation}




