application_locations_homepage:
    path:     /
    defaults: { _controller: applicationLocationsBundle:Default:index }

application_equipmnet_add:
    path:   /equipmentadd
    defaults: { _controller: applicationLocationsBundle:Location:add}

application_equipment_save:
    path:   /equipment/add
<<<<<<< HEAD
    defaults: { _controller: applicationLocationsBundle:Location:saveLocation}


=======
    defaults: { _controller: applicationLocationsBundle:Location:saveEquipment}

equipmnet_add:
    path:   /equipmentadd
    defaults: { _contoller: applicationLocationBundle:Location:add}
>>>>>>> 26a73e160a57223db039a74d038029695ab6d793


